### ISSUE TITLE
revendor upstream

### ISSUE THREAD

**Issue by oconnor663** [oconnor663/kangarootwelve_xkcp.rs#1]
There are some new commits, and it looks like the struct alignments might be simplified.

**Comment by gvanas** [comment]
Yes indeed, sorry, I should have communicated about this but then I got distracted.

The main reason for the simplified structure is explained [here](https://github.com/XKCP/K12/pull/4#issuecomment-613322850). I am happy if this can also simplify your Rust bindings.

**Comment by oconnor663** [comment]
No worries. I don't know if I mentioned before, but the previous headers actually created a typedef whose size was not a multiple of its alignment. I didn't know such a thing was possible in C, and it led to [this bindgen issue](https://github.com/rust-lang/rust-bindgen/issues/1753) and [this StackOverflow answer](https://stackoverflow.com/a/60819006/823869).

**Comment by oconnor663** [comment]
I just pushed some revendoring commits. I do notice a performance penalty on [my 1 KiB benchmark](https://github.com/oconnor663/kangarootwelve_xkcp.rs/blob/master/benches/bench.rs#L52-L55), where previously it was 763 MB/s and now it's 620 MB/s.

**Comment by gvanas** [comment]
Yes, I guess that makes sense if you use Init/Update/Final functions. Not sure how to improve this without going back to an aligned and implementation-dependent state.

Note that the plain `KangarooTwelve()` function should not have any performance penalty at all. But I guess it is not convenient for a streamable interface.

**Comment by oconnor663** [comment]
Maybe we could always use a 64-byte alignment and call it a day? :)

**Comment by gvanas** [comment]
The problem is a bit more subtle. It is not only about alignment, but also about how the state is represented. E.g., on 32-bit platforms, the state is bit-interleaved; on AVX2, the state is stored in a rather specific way. This interacts badly with the functions that enable/disable CPU features introduced in [this commit](https://github.com/XKCP/K12/commit/1aa23f84369ad218321c95d8a1c1402cc2f709ae).

Alternatively, we could go back to implementation-dependent states and choose one of the following:
- forbid changing CPU features after the first call to any K12 function;
- add export/import functions that convert to/from a canonical representation, should the user want to change CPU features dynamically.

Actually, I am slightly in favor of this last option. What do you think?

@mumbleskates do you have an opinion (since you introduced these functions)?

**Comment by oconnor663** [comment]
In https://github.com/oconnor663/blake2_simd and https://github.com/BLAKE3-team/BLAKE3, what we've done is keep an untransposed, unaligned version of the state on the stack, and then transpose it into a fancy representation when one of the wide compression functions is called. Since that transposition isn't free, we put the block loop _inside_ the implementation-specific code, so the API there takes a "how many blocks should I compress" parameter, amortizing the transposition cost over that many blocks. (K12 might be able to assume that 8192-byte chunks are always compressed whole, and omit the parameter?) I'm not sure this exactly the same AVX2-specific representation you're describing, but maybe a similar approach could work. Anyway, this would be a pretty big refactoring.

**Comment by gvanas** [comment]
Thanks for the suggestion. I will have a look.

**Comment by mumbleskates** [comment]
My opinion is that we should NOT support changing the vectorization mode while instances are in use, and it should be in the contract that this is unsupported. Changing the vectorization mode while a hash is in use is, to put it one way, very silly, and I cannot imagine any valid use case for doing that.

It's conceivable that this could be non-obvious and possibly bite someone, but I would be satisfied with loud documentation warnings that those functions are not designed to be played around with willy-nilly during runtime.

~~It also appears to be of critical importance in performance that the struct alignment is honored in the public API. Commit b120009 represents a **HUGE** performance regression with its failure to align the state structs correctly (i'm a little surprised my compiler makes it work at all).~~

~~I ran the XKCP/K12 self-test before and after the alignment change:~~
~~On commit b4f4345: `user    3m30.209s`~~
~~On commit b120009 with the call to `testKangarooTwelveWithChangingCpuFeatures()` commented out: `user    12m58.933s`~~

**Comment by mumbleskates** [comment]
~~Oh boy. On further review I still cannot get it to go faster on this commit, even by adding an alignment annotation, using either clang 9.0.1-6 or gcc 9.2.1. Using a different actual struct in the public API may be discarding optimizations.~~

**Comment by mumbleskates** [comment]
~~So what I'm seeing is a big performance regression in `KangarooTwelve 0 1`, which is calling Update one byte at a time, on that commit. Currently trying to determine what the root cause of this is, and I'm as of right now unsure if it's related to alignment, alignment-based optimizations, or something else.~~

**Comment by mumbleskates** [comment]
I'm sorry. I've seen what is going on between the internal and external instances now with import() and export(). That's my bad for missing this. My apologies for the noise, I should be sleeping better.

I would argue pretty strongly against doing this very expensive marshaling operation like this, especially since it is only to support a use case (changing vectorization instruction set on the fly) which does not actually exist in the wild.

**Comment by oconnor663** [comment]
Would it be simpler to store the instruction set flags in the struct itself, provide an alternative initialization function that sets those flags, and then just not provide any interface for changing those flags after initialization?

**Comment by mumbleskates** [comment]
Maybe. Full disclosure, I played around and made a quadruply-compiled version of the library with symbol replacement and all that jazz before runtime implementation selection hit K12 master; in my implementation I just added a virtual class for the implementation to a struct and used C++ runtime dispatch to find functions for that instruction set, so it was in essence determined pretty much the same way.

It worked ok, but I was more than happy to delete 900 lines of macro garbage and use the official version of the same idea.

For the time being I feel like the best course might look like https://github.com/XKCP/K12/pull/7

**Comment by gvanas** [comment]
> Would it be simpler to store the instruction set flags in the struct itself, provide an alternative initialization function that sets those flags, and then just not provide any interface for changing those flags after initialization?

That would too much complexity IMHO.

**Comment by oconnor663** [comment]
I see that https://github.com/XKCP/K12/commit/7a172582bfa501015c91eb68dd6c749342f02dea just landed upstream. Let's keep this issue open, and maybe someone can ping it when it looks like things are pretty stable?

**Comment by gvanas** [comment]
As far as I am concerned, with the requirement of being able to select CPU features ad libitum removed, the public structure is stable now. (Sorry if that means switching back your Rust bindings to alignment constraints similar to the previous ones.)

Anyway, a big thanks to both of you!

**Comment by mumbleskates** [comment]
Bump: Nothing has changed for a while, and it doesn't seem like it's about to any time soon

**Comment by oconnor663** [comment]
https://github.com/XKCP/K12/commit/63a5255e95abdc2d2ef132d34b38cd1f57cbacca just landed yesterday though :-D

**Comment by mumbleskates** [comment]
Everything from 7a17258 through 2f19845 + is broadly compatible; the generic64 structs are all the same, the signatures are the same, and I'm not aware of any other changes your bindings would possibly need to adapt to.

**Comment by oconnor663** [comment]
Cool. The main thing I'm trying to pay attention to is the build commands on Windows. To avoid a build-time dependency on XSLT, this crate re-implements the build in terms of `build.rs` / the `cc` crate. I still need to bring the Windows build up to speed with the last set of changes. I'll give it a shot.

**Comment by oconnor663** [comment]
An implementation note: The trouble caused by using an aligned typedef in FFI is worse than I thought. On GCC, it produces a type whose size is not a multiple of its alignment, which `bindgen` cannot handle. (This is the previously known issue described at https://github.com/rust-lang/rust-bindgen/issues/1753.) However on MSCV, where we translate `ALIGN(x)` to `__declspec(align(x))`, it works differently! It does the "right" thing and increases the size of the type :( We didn't have to deal with this when the 64-bit build didn't work on Windows at all, but now we have to deal with it.

I expect this to be a painful issue for anyone else who tries to make bindings against this C code. If we could avoid it somehow, for example by always making the KangarooTwelve_FStruct size 256 and align 64 when targeting a 64-bit platform, that would be a big help.

**Comment by oconnor663** [comment]
The workarounds for this just landed in master. 09ca09905ac058ca148fe39413d448d43b23df24 represents the old pain that was already understood. 9fd484de8f24b4483f2c4a0d1f30546595a093d4 represents the new pain on Windows.

**Comment by mumbleskates** [comment]
I looked around at this, it's pretty weird. The problem seems to be that the struct type `KangartooTwelve_FStruct` is not annotated to be aligned, but the typedef `KangarooTwelve_F` *is*.

In essence, the definitions in KangarooTwelve:

```
ALIGN(KeccakP1600_stateAlignment) typedef struct KangarooTwelve_FStruct {
    uint8_t state[KeccakP1600_stateSizeInBytes];
    uint8_t byteIOIndex;
    uint8_t squeezing;
} KangarooTwelve_F;

typedef struct KangarooTwelve_InstanceStruct {
    KangarooTwelve_F queueNode;
    KangarooTwelve_F finalNode;
    size_t fixedOutputLength;
    size_t blockNumber;
    unsigned int queueAbsorbedLen;
    int phase;
} KangarooTwelve_Instance;
```
...are equivalent to:
```
typedef struct KangarooTwelve_FStruct {
    uint8_t state[KeccakP1600_stateSizeInBytes];
    uint8_t byteIOIndex;
    uint8_t squeezing;
} KangarooTwelve_F;

typedef struct KangarooTwelve_InstanceStruct {
    ALIGN(KeccakP1600_stateAlignment) KangarooTwelve_F queueNode;
    ALIGN(KeccakP1600_stateAlignment) KangarooTwelve_F finalNode;
    size_t fixedOutputLength;
    size_t blockNumber;
    unsigned int queueAbsorbedLen;
    int phase;
} KangarooTwelve_Instance;
```

The inner state struct is not inherently aligned. If it were aligned in its own right, the compiler would pad its size to 256 and the rest of the fields in `KangarooTwelve_Instance` would get bumped out to the 512 offset instead of going immediately after `finalNode.squeezing`, increasing the size of the Instance struct by 64 bytes in a way that's definitely not essential for the library.

So the align annotation on the typedef doesn't stick to its use as a type at all, only the member when it's put into another struct by that name... ~~and even then, only if there are any fields of different types. (`sizeof(struct {KangarooTwelve_F a; KangarooTwelve_F b;})` is 404; `sizeof(struct {KangarooTwelve_F a; KangarooTwelve_F b; bool wtf;})` is 512 😰).~~ *edit: Apparently this only applies for things like `sizeof(std::array<KangarooTwelve_F, 2>)`, which is 404; for C style arrays it's even worse: `sizeof(KangarooTwelve_F[2])` is 448: only the final array type is aligned.*

It's messy, unintuitive, and gross, but it's *correct*; the size of the `KangarooTwelve_F` type is, in fact, 202. The fact that the typedef annotation works in a way that deeply confuses bindgen is possibly a bug, but I also think it's preferable to write it in a clearer way that *doesn't* confuse it. If it would help this project and if there's nothing I'm missing, I would heartily advocate for changing the alignment annotations to apply to the fields of `KangarooTwelve_Instance` instead of the typedef, as shown above: it's equivalent, and it's clearer about what is happening.

**Comment by oconnor663** [comment]
@mumbleskates I didn't even know you could explicitly align struct fields :) If `bindgen` can figure it out, I'd be happy to re-vendor that change.

**Comment by oconnor663** [comment]
I've just released version 0.1.2 of this project, which includes the latest code from upstream. I'll go ahead and close this issue, but please do reopen one when there's more code to pull.

**Comment by gvanas** [comment]
Thanks for the analysis.

As far as I can tell, the root requirement is that `KangarooTwelve_FStruct.state` must be aligned. Beyond this, I am open to any solution that would simplify bindings and improve readability.

**Comment by mumbleskates** [comment]
hello @oconnor663 ! see if that helps any.

**Comment by oconnor663** [comment]
Yes! We don't need any manual tweaks to bindgen output anymore! I've already landed another revendoring in master :) Thanks a million!

**Comment by mumbleskates** [comment]
awesome!
